### PR TITLE
Field names with spaces causing syntax errors. 

### PR DESCRIPTION
**Pull request by OskarStark**
See #213

### CODE REVIEW

**Comment by javiereguiluz** [comment]
I've been digging a bit about this. The database column names are less restrictive than entity property names. The reason is that properties are PHP variables and column names are database responsibility.

For example, you can use `call-limit` as a column name, but not as a property name (see http://www.doctrine-project.org/jira/browse/DDC-1288).

So we could apply the usual regular expression to check if some value is a valid PHP variable name:

```php
private function isValidFieldName($name)
{
    return preg_match('/^[a-zA-Z_\x7f-\xff][a-zA-Z0-9_\x7f-\xff]*$/', $name, $matches);
}
```

@OskarStark, what do you think about giving a final boost to this two-year old issue to finish it? Thanks!

**Comment by OskarStark** [comment]
i absolutely agree with you @javiereguiluz 

my problem is that the current code (as i said) can produce syntax errors.
IMO we should be failsafe on the php level, the database itself should throw an error if the fieldname is invalid.

but the goal for me is that the syntax should be correct anyway

**Comment by OskarStark** [comment]
@javiereguiluz shall i provide a PR with this change?

from where do you get this method?

**Comment by javiereguiluz** [comment]
Yes please, provide a PR and I'll review it. I took the method from StackOverflow and verified it with the PHP manual.

**Comment by OskarStark** [comment]
@javiereguiluz i added you as collaborator.

i commited my changed in the branch ```fieldname-check````

when i add phpunit the test will stuck for a long time...
when i execute the tests against ```master``` it is very fast.

can you please have a look?
maybe there are some problems withe the closure and the referenced ```$matches``` var in the ```preg_match```

thank you

**Comment by OskarStark** [comment]
bildschirmfoto 2015-07-19 um 17 43 57
bildschirmfoto 2015-07-19 um 17 46 31

**Comment by OskarStark** [comment]
hmm, with this commit the tests are running @javiereguiluz 

https://github.com/OskarStark/SensioGeneratorBundle/commit/79c6a430a0f992dd4440144f87b93010b3ad9300

**Comment by OskarStark** [comment]
i added a new PR with the idea of @javiereguiluz here: #394

**Comment by javiereguiluz** [comment]
Closing it in favor of #394

**Pull request closed without merging**
