### PR TITLE
use Trusty to be able to test using HHVM

### PR DESCRIPTION
**Pull request by xabbuh**

### CODE REVIEW

**Comment by xabbuh** [comment]
Hm, looks like we now cannot test PHP 5.3 anymore.

**Comment by guilliamxavier** [comment]
@xabbuh Cause: https://github.com/travis-ci/travis-ci/issues/7693
Possible solution: https://github.com/travis-ci/travis-ci/issues/7693#issuecomment-305251970 -> https://github.com/travis-ci/travis-ci/issues/7712#issuecomment-300553336
i.e. override `dist: trusty` to `dist: precise` only for `- php: 5.3`

**Comment by xabbuh** [comment]
@guilliamxavier Indeed, this helped a lot. Thank you very much! Tests are green again.

**Comment by fabpot** [comment]
Thank you @xabbuh.

**Pull request closed without merging**
