### PR TITLE
Allows digits in validateEntityName

### PR DESCRIPTION
**Pull request by intermike**

### CODE REVIEW

**Comment by OskarStark** [comment]
Could you please add a test for this change?

**Comment by intermike** [comment]
I am not sure I did it properly and fully. Please check. Thanks.

**Comment by intermike** [comment]
Btw, I did this new test without primal change and phpunit has been just stuck without any error messages. Is that normal behaviour?

clipboard01

**Comment by javiereguiluz** [comment]
@intermike after applying your change tests work for me (and for Travis CI service too):

phpunit_tests

So I'm going to merge this change. Thanks for your contribution.

**Pull request closed without merging**
