### PR TITLE
Fix directory generation for tests in generate:bundle

### LINKED ISSUE #530: generate:bundle does not generate the right tests directory structure
Hello,

To my understanding, the tests directory should follow the same structure as the src directory. If we want to test the file `src/Product/AppBundle/Controller/DefaultController.php`we should have a test file located in `tests/Product/AppBundle/Controller/DefaultControllerTest.php`.

This is even more true when using composer autoloading feature.

## Issue
If I'm generating a new bundle using the following command:

```
php bin/console generate:bundle                  \
                  --dir=src                      \
                  --namespace=Product/AppBundle  \
                  --bundle-name=ProductAppBundle \
                  --format=yml
```

It will generate the **good** `src` directory structure:
```
src
└── Product
    └── AppBundle
        ├── Controller
        │   └── DefaultController.php
        ├── ProductAppBundle.php
        └── Resources
            ├── config
            │   ├── routing.yml
            │   └── services.yml
            └── views
                └── Default
                    └── index.html.twig

```

But a **wrong** `tests`directory structure:

```
tests
└── ProductAppBundle
    └── Controller
        └── DefaultControllerTest.php
```
with a **wrong namespace**: `namespace Product\AppBundle\Tests\Controller;`

## Suggestion

The DefaultControllerTest should be located in:
```
tests
└── Product
    └── AppBundle
        └── Controller
            └── DefaultControllerTest.php
```
with the namespace: `Tests\Product\AppBundle\Controller`.

This is not big of an issue for phpunit because it doesn't care much of the tests directory structure.
This is only an issue when you want to use composer autoloading because it can not find the class. 

## Alternative

I don't think it's a good idea but if we want to keep the current test directory structure, we should add a new autoload-dev each time we generate a bundle:
```
"autoload-dev": {
        "psr-4": {
            "Product\\AppBundle\\Tests\\": "tests/ProductAppBundle"
        }
    },
```

### PR DESCRIPTION
**Pull request by juliendufresne**
Fixes #530

### CODE REVIEW

**Comment by juliendufresne** [comment]
Any thought about this?

**Review by HeahDude — APPROVED** [review]
LGTM 👍

**Comment by juliendufresne** [comment]
Who should I ping to get this merged? :)

**Comment by fabpot** [comment]
I would create a dedicated `Tests\\` namespace as it allows to exclude those files from the prod autoloading.

**Comment by HeahDude** [comment]
@fabpot can we afford that change while this bundle is still compatible with symfony 2.7?

**Comment by juliendufresne** [comment]
@fabpot It looks like what I did, Maybe I wasn't clear in my Issue description #530 
This PR transforms

```
# Path (...ProductApp.. => ...Product/App...)
Before : tests/ProductAppBundle/Controller/DefaultControllerTest.php
After  : tests/Product/AppBundlee/Controller/DefaultControllerTest.php
# Namespace
Before : namespace Product\AppBundle\Tests\Controller;
After  : namespace Tests\Product\AppBundle\Controller;
```

But only for non shared projects.

**Comment by juliendufresne** [comment]
You can close it. Obviously you won't merge it (even if it's a bugfix) and with the Symfony4 comming on, this repo will no longer be useful anyway

**Comment by fabpot** [comment]
Closing this pull request as this bundle is now obsolete. Please, use the maker bundle instead.

**Pull request closed without merging**
