### PR TITLE
Update generate_bundle.rst

### PR DESCRIPTION
**Pull request by DavyGab**

### CODE REVIEW

**Comment by OskarStark** [comment]
:-1:

**Comment by DavyGab** [comment]
??
With Symfony 3, it's not app/console !

**Comment by xabbuh** [comment]
That's true, but for Symfony 2 it's still `app/console` and this bundle works with both versions.

**Comment by DavyGab** [comment]
Ok. I thought I changed only for Symfony 3... Because I lost time to "find solution".

**Comment by fabpot** [comment]
Closing as there is no good way to fix that.

**Pull request closed without merging**
