### PR TITLE
Allow Symfony 4

### PR DESCRIPTION
**Pull request by dunglas**

### CODE REVIEW

**Comment by fabpot** [comment]
Not sure about this one as the structure in Symfony 4 (via Flex) will be very different, so I doubt that this will work just by adding this.

**Comment by dunglas** [comment]
@fabpot still useful if you use the standard edition with Symfony 4 (legacy projects for instance).

**Comment by cbdiesse** [comment]
I don't understand why Symfony 4 applications cannot use bundles for modularity and features extension for large web applications. flex not seem concerned by those features and then internal bundle generator must not be affected unless S4 bundles directory structure is actually unknown.

**Comment by fabpot** [comment]
Closing as symfony/maker-bundle should be used instead. Standard edition is not available for Symfony 4 anyway.

**Pull request closed without merging**
