### PR TITLE
Make generated classes final by default.

### PR DESCRIPTION
**Pull request by WouterSioen**
Resources:

http://ocramius.github.io/blog/when-to-declare-classes-final/
http://verraes.net/2014/05/final-classes-in-php/

### CODE REVIEW

**Comment by WouterSioen** [comment]
@fabpot @weaverryan any opinions on this?

**Comment by weaverryan** [comment]
Hmm I'm -1, mostly because I don't see much benefit - final is more important when you're building code you'll share. I think a lot of users will wonder what the significance is of the final- why you need it in symfony (You don't need it, but when people see it, they might assume so).

For me, little benefit, but it may confuse people. People who understand final can add it if they wish to.

Cheers!

**Comment by WouterSioen** [comment]
Hmm, I get the confusing users part, but it's a part of the language, so I guess PHP developers should not be confused by it, and if they are, it's time for them to learn the keyword.

The final keyword is ment to show that a class should not be extended. Controllers are one of the best examples of classes you'll never extend. If there's one type of classes in your application that are logical to have the final keyword, it's your controller classes.

But again, I get your point too, and I get it if you close this PR. It would be just nice to see the final keyword a little more in PHP code. It's great to enforce composition instead off massive inheritance.

**Comment by fabpot** [comment]
Closing this PR as I share @weaverryan's point of view.

**Pull request closed without merging**
