### PR TITLE
[GenerateBundle] render function Default controller doesn't find template.

### PR DESCRIPTION
**Pull request by raffaelecarelle**
Hi guys,

after generating acme bundle the index view doesn't match with the exception: Unable to find template "Acme:Default:index.html.twig".

I fixed this replacing with

$this->render('@Acme/Default/index.html.twig');

I've remove Bundle suffix and replace ":" with "/".

I hope I did well.

Best regards.

Raffaele C.

### CODE REVIEW

**Review by OskarStark — CHANGES_REQUESTED** [review]
Please don’t change the chmod of the file

**Comment by raffaelecarelle** [comment]
> Please don’t change the chmod of the file

You're right. I'm sorry. How can I do now? Re-send the pull request?

**Comment by OskarStark** [comment]
You can do:
- `change the chmod`
- `git add Resources/skeleton/bundle/DefaultController.php.twig`
- `git commit --amend`
- `git push --force`

**Comment by raffaelecarelle** [comment]
> You can do:
> 
> * `change the chmod`
> * `git add Resources/skeleton/bundle/DefaultController.php.twig`
> * `git commit --amend`
> * `git push --force`

Thanks! 

I did it :)

**Comment by raffaelecarelle** [comment]
Hi @OskarStark ,

have you news about it? :)

**Comment by fabpot** [comment]
Closing this pull request as this bundle is now obsolete. Please, use the maker bundle instead.

**Pull request closed without merging**
