### PR TITLE
Fix Problem with Symfony 3  CRUD Genarator

### PR DESCRIPTION
**Pull request by ahmadsajid1989**
There was an error while generating CRUD with Command and this updates fixed the issue with date, datetime and time type

### CODE REVIEW

**Comment by OskarStark** [comment]
looks ok to me :+1:

**Comment by pmithrandir** [comment]
When will it be merged ?

**Comment by xabbuh** [comment]
looks like a duplicate of #431

**Comment by fabpot** [comment]
indeed

**Pull request closed without merging**
