### PR TITLE
avoid deprecated method

### PR DESCRIPTION
**Pull request by garak**

### CODE REVIEW

**Comment by xabbuh** [comment]
`configureOptions()` is not available on Symfony 2.6.

**Comment by garak** [comment]
@xabbuh this bundle is currently requiring ~2.6

**Comment by phansys** [comment]
@xabbuh, the latest release for Symfony standard 2.6 (2.6.9) has a [requirement for ```~2.3```](https://github.com/symfony/symfony-standard/blob/v2.6.9/composer.json#L24) and this PR was made against master.

**Comment by xabbuh** [comment]
That's true, but nothing is preventing one to use the bundle with Symfony 2.3.

**Comment by phansys** [comment]
I think that premise applies to a lot of other situations, but I agree that here could be worst since this is a code generator tool.
Maybe is possible to check what version of Symfony is installed and generate the appropriate code block for each case.

**Comment by phansys** [comment]
I just found a previous PR addressing this.
Duplicate of #348, which is also compatible with `< 2.7`.

**Comment by garak** [comment]
Thanks @phansys

**Pull request closed without merging**
