### PR TITLE
Remove dev minimum stability

### PR DESCRIPTION
**Pull request by hason**

### CODE REVIEW

**Comment by xabbuh** [comment]
What about using the `--prefer-stable` Composer option instead? Changing the minimum stability setting here will make it harder to run tests against upcoming releases of dependency packages.

**Comment by HeahDude** [comment]
@hason Can you address @xabbuh's comment?

**Comment by HeahDude** [comment]
ping @hason :)

**Comment by HeahDude** [comment]
Closing here per @xabbuh's comment.

**Pull request closed without merging**
