### PR TITLE
Update generate_bundle.rst

### PR DESCRIPTION
**Pull request by milardovich**
Please change app/console for bin/console for 3.0 version

### CODE REVIEW

**Comment by OskarStark** [comment]
:-1: please use the search functionality, this PR was proposed several times, we won't accept it.

maybe @xabbuh can link the other issues

**Comment by javiereguiluz** [comment]
If one user asks something ... he may be wrong. If lots of users ask for the same thing ... we are probably wrong and need to fix something.

**Comment by xabbuh** [comment]
Imo the note added at the top of all chapters (see #460) should be enough.

**Comment by OskarStark** [comment]
:+1:

**Comment by javiereguiluz** [comment]
@milardovich thanks for proposing this change. This issue is a bit tricky because the bundle is compatible both with Symfony 2 and 3. Right now we display a note about this at the top of each page:

generator_bundle

That's why I'm closing this as "won't fix" for now. But we'll keep thinking about ways to improve this. Thanks!

**Pull request closed without merging**
